language: python
python:
  - 2.7
  - 3.6
before_install:
  - sudo add-apt-repository ppa:alex-p/tesseract-ocr
  - sudo apt-get -qq update
  - sudo make deps-ubuntu
install:
  - make deps-pip test-deps-pip
script:
  - make test
