language: python
python:
  # - 2.7
  - 3.6
before_install:
  - sudo apt-get -qq update
  - make deps-ubuntu
install:
  - pip -r requirements_dev.txt
  - pip -r requirements_test.txt
  - make assets
script:
  - make test
