language: python
python:
  - 3.4
  - 3.6
  - 3.7-dev
before_install:
  - sudo apt-get -qq update
  - make deps-ubuntu
install:
  - make deps-test assets install PIP_INSTALL="pip install -e"
script:
  - make test PYTHON="coverage run"
  - coverage report -m
after_success:
  - codecov
