version: 2

jobs:

  test-python35:
    docker:
      - image: python:3.5.3
    working_directory: ~/ocrd-core
    steps:
      - checkout
      - run: make deps-test install
      - run: make test

  test-python36:
    docker:
      - image: python:3.6.0
    working_directory: ~/ocrd-core
    steps:
      - checkout
      - run: make deps-test install
      - run: make test

  test-python37:
    docker:
      - image: python:3.7.1
    working_directory: ~/ocrd-core
    steps:
      - checkout
      - run: make deps-test install
      - run: make test

  deploy:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker      # https://circleci.com/docs/2.0/building-docker-images/
      - run: make docker
      - run: make docker-gpu
      - run:
          name: Login to Docker Hub
          command: echo "$DOCKERHUB_PASS" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
      - run: docker push ocrd/core
      - run: docker push ocrd/core-gpu

workflows:
  version: 2
  build-master:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
  test-pull-request:
    jobs:
      - test-python35:
          filters:
            branches:
              ignore: master
      - test-python36:
          filters:
            branches:
              ignore: master
      - test-python37:
          filters:
            branches:
              ignore: master
